[versions]
kotlin = "1.9.10"
compileSdk = "34"
minSdk = "21"
dokka = "1.9.0"

[libraries]
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version = "1.7.3" }

okio = { module = "com.squareup.okio:okio", version = "3.5.0" }
coil = { module = "io.coil-kt:coil-compose", version = "2.7.0" }

junit = { module = "junit:junit", version = "4.13.2" }
robolectric = { module = "org.robolectric:robolectric", version = "4.9" }
